apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce-dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'user-service'
        metrics_path: '/user-service/actuator/prometheus'
        static_configs:
          - targets: ['user-service:8700']
      
      - job_name: 'product-service'
        metrics_path: '/product-service/actuator/prometheus'
        static_configs:
          - targets: ['product-service:8500']
      
      - job_name: 'payment-service'
        metrics_path: '/payment-service/actuator/prometheus'
        static_configs:
          - targets: ['payment-service:8400']
      
      - job_name: 'order-service'
        metrics_path: '/order-service/actuator/prometheus'
        static_configs:
          - targets: ['order-service:8300']
      
      - job_name: 'shipping-service'
        metrics_path: '/shipping-service/actuator/prometheus'
        static_configs:
          - targets: ['shipping-service:8600']
      
      - job_name: 'proxy-client'
        metrics_path: '/app/actuator/prometheus'
        static_configs:
          - targets: ['proxy-client:8900']

