apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: ElasticsearchLogs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: ecommerce-logs-*
    jsonData:
      esVersion: 7
      timeField: "@timestamp"
      interval: Daily
      logMessageField: message
      logLevelField: log_level.keyword
    editable: true
