apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: selimhorri/favourite-service-ecommerce-boot:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8800
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/ecommerce_stage_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "ecommerce"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: SPRING_ZIPKIN_BASE-URL
          value: "http://zipkin:9411"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_FLYWAY_TABLE
          value: "flyway_favourite_schema_history"
        - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
          value: "true"
        - name: SPRING_FLYWAY_REPAIR_ON_MIGRATE
          value: "true"
        - name: SPRING_FLYWAY_IGNORE_MISSING_MIGRATIONS
          value: "true"
        - name: SPRING_FLYWAY_IGNORE_IGNORED_MIGRATIONS
          value: "true"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "none"
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8800
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8800
          initialDelaySeconds: 90
          periodSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ecommerce-stage
spec:
  type: NodePort
  selector:
    app: favourite-service
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP

