apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds":"10","service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold":"2","service.beta.kubernetes.io/do-loadbalancer-healthcheck-path":"/actuator/health","service.beta.kubernetes.io/do-loadbalancer-healthcheck-port":"8080","service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol":"http","service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds":"5","service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold":"3","service.beta.kubernetes.io/do-loadbalancer-protocol":"http"},"name":"api-gateway","namespace":"ecommerce-stage"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"api-gateway"},"type":"LoadBalancer"}}
    kubernetes.digitalocean.com/load-balancer-id: 27abf5d6-5c49-4c52-b92b-69f7617d6a6c
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "10"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: /actuator/health
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-type: REGIONAL
  creationTimestamp: "2025-11-30T17:28:44Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: api-gateway
  namespace: ecommerce-stage
  resourceVersion: "97962"
  uid: 8fb02e5a-3631-4a67-999c-1a7f36adb793
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.245.228.25
  clusterIPs:
  - 10.245.228.25
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31356
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 24.199.64.197
      ipMode: VIP
    - ip: 2604:a880:400:d1:0:3:4acd:6001
      ipMode: VIP
