apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
      - name: proxy-client
        image: localhost:5000/proxy-client:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8900
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: ecommerce-dev
spec:
  type: NodePort
  selector:
    app: proxy-client
  ports:
  - port: 8900
    targetPort: 8900
    protocol: TCP

