name: Stage, on PR Java CI/CD of api-gateway, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'api-gateway/**'
      - 'pom.xml'
      - '.github/workflows/api-gateway-pipeline-stage-pr.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: api-gateway
      service_path: api-gateway
    secrets: inherit
