name: Prod, on PUSH Java CI/CD of api-gateway-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ master ]
    paths:
      - 'api-gateway/**'
      - 'pom.xml'
      - '.github/workflows/api-gateway-pipeline-prod-push.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: api-gateway
      service_path: api-gateway
      dockerfile_path: api-gateway/Dockerfile
      environment: prod
      docker_image_name: api-gateway-ecommerce-boot
      skip_deploy: false
    secrets: inherit
