name: Stage, on PUSH Java CI/CD of cloud-config-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'cloud-config/**'
      - 'pom.xml'
      - '.github/workflows/cloud-config-pipeline-stage-push.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: cloud-config
      service_path: cloud-config
      dockerfile_path: cloud-config/Dockerfile
      environment: stage
      docker_image_name: cloud-config-ecommerce-boot
      skip_deploy: false
    secrets: inherit
