name: Stage, on PR Java CI/CD of cloud-config, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'cloud-config/**'
      - 'pom.xml'
      - '.github/workflows/cloud-config-pipeline-stage-pr.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: cloud-config
      service_path: cloud-config
    secrets: inherit
