name: Stage, on PUSH Java CI/CD of favourite-service-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'favourite-service/**'
      - 'pom.xml'
      - '.github/workflows/favourite-service-pipeline-stage-push.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: favourite-service
      service_path: favourite-service
      dockerfile_path: favourite-service/Dockerfile
      environment: stage
      docker_image_name: favourite-service-ecommerce-boot
      skip_deploy: false
    secrets: inherit
