name: Prod, on PR Java CI/CD of favourite-service, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'favourite-service/**'
      - 'pom.xml'
      - '.github/workflows/favourite-service-pipeline-prod-pr.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: favourite-service
      service_path: favourite-service
    secrets: inherit
