name: Stage, on PUSH Java CI/CD of order-service-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'order-service/**'
      - 'pom.xml'
      - '.github/workflows/order-service-pipeline-stage-push.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: order-service
      service_path: order-service
      dockerfile_path: order-service/Dockerfile
      environment: stage
      docker_image_name: order-service-ecommerce-boot
      skip_deploy: false
    secrets: inherit
