name: Stage, on PR Java CI/CD of order-service, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'order-service/**'
      - 'pom.xml'
      - '.github/workflows/order-service-pipeline-stage-pr.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: order-service
      service_path: order-service
    secrets: inherit
