name: Stage, on PUSH Java CI/CD of payment-service-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'payment-service/**'
      - 'pom.xml'
      - '.github/workflows/payment-service-pipeline-stage-push.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: payment-service
      service_path: payment-service
      dockerfile_path: payment-service/Dockerfile
      environment: stage
      docker_image_name: payment-service-ecommerce-boot
      skip_deploy: false
    secrets: inherit
