name: Stage, on PR Java CI/CD of payment-service, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'payment-service/**'
      - 'pom.xml'
      - '.github/workflows/payment-service-pipeline-stage-pr.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: payment-service
      service_path: payment-service
    secrets: inherit
