name: Stage, on PR Java CI/CD of product-service, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'product-service/**'
      - 'pom.xml'
      - '.github/workflows/product-service-pipeline-stage-pr.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: product-service
      service_path: product-service
    secrets: inherit
