name: Stage, on PUSH Java CI/CD of product-service-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'product-service/**'
      - 'pom.xml'
      - '.github/workflows/product-service-pipeline-stage-push.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: product-service
      service_path: product-service
      dockerfile_path: product-service/Dockerfile
      environment: stage
      docker_image_name: product-service-ecommerce-boot
      skip_deploy: false
    secrets: inherit
