name: Prod, on PR Java CI/CD of proxy-client, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'proxy-client/**'
      - 'pom.xml'
      - '.github/workflows/proxy-client-pipeline-prod-pr.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: proxy-client
      service_path: proxy-client
    secrets: inherit
