name: Prod, on PR Java CI/CD of service-discovery, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'service-discovery/**'
      - 'pom.xml'
      - '.github/workflows/service-discovery-pipeline-prod-pr.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: service-discovery
      service_path: service-discovery
    secrets: inherit
