name: Stage, on PUSH Java CI/CD of service-discovery-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'service-discovery/**'
      - 'pom.xml'
      - '.github/workflows/service-discovery-pipeline-stage-push.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: service-discovery
      service_path: service-discovery
      dockerfile_path: service-discovery/Dockerfile
      environment: stage
      docker_image_name: service-discovery-ecommerce-boot
      skip_deploy: false
    secrets: inherit
