name: Stage, on PR Java CI/CD of service-discovery, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'service-discovery/**'
      - 'pom.xml'
      - '.github/workflows/service-discovery-pipeline-stage-pr.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: service-discovery
      service_path: service-discovery
    secrets: inherit
