name: Stage, on PUSH Java CI/CD of shipping-service-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ stage ]
    paths:
      - 'shipping-service/**'
      - 'pom.xml'
      - '.github/workflows/shipping-service-pipeline-stage-push.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-service-pipeline.yml
    with:
      service_name: shipping-service
      service_path: shipping-service
      dockerfile_path: shipping-service/Dockerfile
      environment: stage
      docker_image_name: shipping-service-ecommerce-boot
      skip_deploy: false
    secrets: inherit
