name: Stage, on PR Java CI/CD of shipping-service, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'shipping-service/**'
      - 'pom.xml'
      - '.github/workflows/shipping-service-pipeline-stage-pr.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: shipping-service
      service_path: shipping-service
    secrets: inherit
