name: Stage, on PR Java CI/CD of user-service, ecommerce-microservice-backend app

on:
  pull_request:
    branches: [ stage ]
    paths:
      - 'user-service/**'
      - 'pom.xml'
      - '.github/workflows/user-service-pipeline-stage-pr.yml'
      - '.github/workflows/reusable-pr-pipeline.yml'
      - '.github/workflows/reusable-service-pipeline.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pr-pipeline.yml
    with:
      service_name: user-service
      service_path: user-service
    secrets: inherit
